project_id = "stjtkvanmlidurmwpdpc"

[functions.register]
verify_jwt = false

[functions.whatsapp-instance]
verify_jwt = true

[functions.whatsapp-webhook]
verify_jwt = false

[functions.send-whatsapp-message]
verify_jwt = true

[functions.conversation-management]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.send-whatsapp-audio]
verify_jwt = true

[functions.send-whatsapp-image]
verify_jwt = true
